### ISSUE TITLE
WorldData removal

### ISSUE THREAD

**Issue by JChudinov** [PeteyChan/SimpleECS#26]
Hi, what was the purpose of deleting static data from querying?  That was quite a handy tool which sligtly violate ECS paradigm, tho still had its usecases. In our production project we use it to determinate augmented reallity marker state in multiple queries. Without this feature we will have to write additional lines of code, which is ofc not what we want :)

**Comment by PeteyChan** [comment]
Hey thanks for trying out my project, I didn't think anyone would think it was worth using it so I'm pretty humbled :) I actually agree with you, having access to data local to the world to use as static data is very useful which is why I added that in the first place. Without it you have to use hacks such as shared components or singleton entities and they don't really represent the idea quite as concisely and they come with additional mental overhead. The reason I removed it was simply because I didn't like the way it was implemented. I felt it didn't show the intent of what's actually happening clearly enough.

```C#
// I just felt looking at this, it wasn't really clear that the in component was world data. You'd have to read the docs or
// have someone tell you

query.Foreach((Entity entity, in float world_float, ref float component) =>  {
    // though having looked at it again, if you prefaced all the world parameters with world_ it's probably not so bad
});
```
I do plan on putting it back in, but in a slightly different way. I'm thinking of adding the world as a first possible argument to the query where you'd be able to get the world data from that. Although it won't be as concise as it was before, there's quite a few benefits to it.
- you can update world data from within the query
- you can create new entity's from within the query, this is especially useful for entities as events
- the intent is clear
- the amount of delegates needed to be generated to use with the Foreach method is reduced which means I can add more component parameters
- a downside is that there would be some small overhead calling that function every entity, but that overhead should only be slightly more expensive than an array lookup

```C#
query.Foreach((World world, Entity entity, ref int component) => {     // something like this
    ref world_float =  ref world.GetData<float>();    // you'd just leave out the ref to make it read only
    world.Get<int>() += 3; // or maybe I'll just mimic the entity's current api so that it's ref world.Get<Data>()
    world_float += 3.5f;
});
```
I'm also wondering if Data is the right word, Resource may be more appropriate. I'd be happy to hear your thoughts on these changes. Sorry that the code base is still in flux, it's why I haven't added any releases. I should probably add that to the read me. 

Also I'm curious if you don't mind how this codebase has been for your project so far and why you chose it. Could give me some insights on how to improve this ;)

**Comment by DigitalOxygen58** [comment]
Hi again and sorry for late responce, ill try to responce more quickly next time. As for this framework decision, first of all, we wanted to use ECS due to the composition over inheritance, splitting logic and data, dynamic composition and so on (unity technologies completly sold out it to us).

 The thing we decided to use ur ECS, well, because its... simple :) In our projects we dont really need uber high performance benifits that most of other frameworks give, we work in unity and code is quite rare appears to be a performance issue, yours framework aint give much overhead and aint reduce the development speed. 
The second reason is unity easy integration: one scene -> one ecs world and you good to go. Ability to mix structs and classes was also mandatory because most of unity features like mesh renderers and colliders are classes.

As to the features, perhaps this topic is not the most appropriate place to place them here :) But the biggest issue was lack of debugging features. Visual studio breakpoints work fine but still archetype analytics are quite hard. I can write out some other thigs here too, but u might want a separate topic to that?

**Comment by DigitalOxygen58** [comment]
p.s. as for Data naming, we wouldn't want to see it named Resource due to unity specific Resources reservation

**Comment by PeteyChan** [comment]
I've added it back, without it it's too much of a pain to work around c# delegate capture. Probably the main reason why I added it in the first place xD
