### ISSUE TITLE
EntityLink document

### ISSUE THREAD

**Issue by bayganik** [PeteyChan/SimpleECS#7]
Can you please describe the purpose of EntityLink?  I am playing around with EgoCS and your framework.

Thank you for sharing this framework.

Kamran

**Comment by PeteyChan** [comment]
Sorry for the late reply. The project has changed quite a lot since then and I simply hadn't got around to updating the Wiki. The original system was all in c# and because of this there was a need for some way to link gameobjects and Entities for use in Unity, hence the entity link. Overall the system was a pain in the arse to use so I ended up scrapping it and wrote something much more Unity friendly. If your still interested I've made some recent changes and updated the wiki to reflect it as well as added an example project with a very rough implementation.

Cheers Pete.

**Comment by bayganik** [comment]
thank you very much.  I've noticed the changes and I am trying to wrap my
head around it.  A simple example would be nice.

Kamran

**Comment by PeteyChan** [comment]
One word of warning, this system isn't that vigorously tested yet so there may be bugs, if you find any let me know. I think I may make a short tutorial over the next couple of days, should help quite alot. I'll leave a comment here when I'm done.

Pete

**Comment by PeteyChan** [comment]
Pushed a new build and finished the tutorial. The tutorial's very basic but covers pretty much everything you need to know. 

Pete
